DDACAssignment/Controllers/FlightBookingController.cs
using DDACAssignment.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDACAssignment.Controllers
{
    public class FlightBookingController : Controller
    {
        // GET: FlightBooking
        public ActionResult Index()
        {
            return View("../Flight/Booking");
        }
        public ActionResult Flight_Booking(string origin, string destination, string date, string price)
        {

            //book the flight here... get the data from html form
            string fclass = Request.Form["flightClass"];
            string fname = Request.Form["flightname"];

            DateTime oDate = DateTime.Now;
            if (date.Equals(""))
                oDate = DateTime.Now;
            else
                oDate = Convert.ToDateTime(date);

            string oDateString = oDate.ToString("yyyy-MM-dd HH:mm:ss.fff");

            float fprice = 260;
            if (fclass.Equals("Economic Class"))
                fprice = 260;
            else if (fclass.Equals("Business Class"))
                fprice = 390;
            else
                fprice = 520;

            String connString = "Server=tcp:uiaflightddac.database.windows.net,1433;Initial Catalog=UIAFlight;Persist Security Info=False;User ID=web_user;Password=Abc123123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
            SqlConnection conn = new SqlConnection(connString);

            conn.Open();
            DateTime myDateTime = DateTime.Now;
            string sqlFormattedDate = myDateTime.ToString("yyyy-MM-dd HH:mm:ss.fff");

            String query = "INSERT INTO [dbo].[FlightBookingHistory] ([Fname],[DateBooking],[DateFlight],[Origin],[Destination],[FClass],[Price],[Status], [PID]) VALUES ('" + fname + "', '" + sqlFormattedDate + "', '" + oDateString + "', '" + origin + "', '" + destination + "', '" + fclass + "', " + fprice + ", 'WAITING' ,'" + Person.p.pid + "')";
            SqlCommand cmd = new SqlCommand(query);
            cmd.CommandType = System.Data.CommandType.Text;
            cmd.Connection = conn;
            cmd.ExecuteNonQuery();

            conn.Close();


            TempData["success"] = "<script>alert('Flight booked succesfully!!!');</script>";



            return View("../Flight/Booking");
        }
    }
}

DDACAssignment/Controllers/FlightHistoryController.cs
using DDACAssignment.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDACAssignment.Controllers
{
    public class FlightHistoryController : Controller
    {
        // GET: FlightHistory
        public ActionResult Index()
        {
            List<FlightBookingHistory> histories = new List<FlightBookingHistory>();

            String connString = "Server=tcp:uiaflightddac.database.windows.net,1433;Initial Catalog=UIAFlight;Persist Security Info=False;User ID=web_user;Password=Abc123123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
            SqlConnection conn = new SqlConnection(connString);

            conn.Open();


            String query = "SELECT * FROM FlightBookingHistory WHERE PID = " + Person.p.pid;


            SqlCommand cmd = new SqlCommand(query);
            cmd.CommandType = System.Data.CommandType.Text;
            cmd.Connection = conn;

            SqlDataReader reader = cmd.ExecuteReader();
            

            while (reader.Read())
            {
               histories.Add(new FlightBookingHistory() {
                    fhid = (int)reader["FHID"],
                    fname = reader["Fname"].ToString(),
                    dataBooking = Convert.ToDateTime(reader["DateBooking"]),
                    dataFlight = Convert.ToDateTime(reader["DateFlight"]),
                    origin = reader["Origin"].ToString(),
                    destination = reader["Destination"].ToString(),
                    fclass = reader["FClass"].ToString(),
                    price = (double) reader["Price"],
                    status = reader["Status"].ToString(),
                });
            }
            ViewBag.Histories = histories;
            return View("../Flight/History");
        }
    }
}

DDACAssignment/Controllers/FlightScheduleController.cs
using DDACAssignment.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDACAssignment.Controllers
{
    public class FlightScheduleController : Controller
    {
        // GET: FlightSchedule
        public ActionResult Index()
        {

            List<FlightSchedule> schedules = new List<FlightSchedule>();

            String connString = "Server=tcp:uiaflightddac.database.windows.net,1433;Initial Catalog=UIAFlight;Persist Security Info=False;User ID=web_user;Password=Abc123123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
            SqlConnection conn = new SqlConnection(connString);

            conn.Open();


            String query = "SELECT * FROM FlightSchedule";


            SqlCommand cmd = new SqlCommand(query);
            cmd.CommandType = System.Data.CommandType.Text;
            cmd.Connection = conn;

            SqlDataReader reader = cmd.ExecuteReader();


            while (reader.Read())
            {
                schedules.Add(new FlightSchedule()
                {
                    fsid = (int)reader["FSID"],
                    fname = reader["Fname"].ToString(),
                    date = Convert.ToDateTime(reader["Date"]),
                    origin = reader["Origin"].ToString(),
                    destination = reader["Destination"].ToString(),
                    status = reader["Status"].ToString(),
                });
            }
            ViewBag.Schedules = schedules;
            return View("../Flight/Schedule");
        }
    }
}

DDACAssignment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Ukraine International Airlines</title>
    
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/sb-admin.css")
    @Styles.Render("~/Content/style.css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/dataTables.bootstrap4.css")
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">

        <img src='@Url.Content("~/Content/Images/flight.jpg")'  height="44px" style="margin-right: 20px;"/>
        @Html.ActionLink("Ukraine International Airlines", "Index", "Home", null, new { @class = "navbar-brand" })
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="@Url.Action("Index", "Home", null)">

                        <i class="fa fa-fw fa-search"></i>
                        <span class="nav-link-text">Home</span>
                    </a>
                </li>

                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">

                    <a class="nav-link" href="@Url.Action("Index", "FlightBooking", null)">
                  
                        <i class="fa fa-fw fa-dashboard"></i>
                        <span class="nav-link-text">Flight Booking</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
                    <a class="nav-link" href="@Url.Action("Index", "FlightSchedule", null)">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">Flight Schedule</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">

                    <a class="nav-link" href="@Url.Action("Index", "FlightHistory", null)">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">Booking History</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav sidenav-toggler">
                <li class="nav-item">
                    <a class="nav-link text-center" id="sidenavToggler">
                        <i class="fa fa-fw fa-angle-left"></i>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="@Url.Action("Index", "Home", null)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-fw fa-bell"></i>
                        <span class="d-lg-none">
                            Alerts
                            <span class="badge badge-pill badge-warning">6 New</span>
                        </span>
                        <span class="indicator text-warning d-none d-lg-block">
                            <i class="fa fa-fw fa-circle"></i>
                        </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="alertsDropdown">
                        <h6 class="dropdown-header">New Alerts:</h6>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index", "Home", null)">
                            <span class="text-success">
                                <strong>
                                    <i class="fa fa-long-arrow-up fa-fw"></i>Ngo you have a new message!
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">Greetings from UIA, you are navigating our...</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="@Url.Action("Index", "Home", null)">
                            <span class="text-danger">
                                <strong>
                                    <i class="fa fa-long-arrow-down fa-fw"></i>Booked flight is near
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">Your booked flight ID001 is around the corner. Enjoy your trip!</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item"href="@Url.Action("Index", "Home", null)">
                            <span class="text-success">
                                <strong>
                                    <i class="fa fa-long-arrow-up fa-fw"></i>Merry Christmas!
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">Merry Christmas Mr.Ngo, we would like to share to you our great deal...</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item small" href="@Url.Action("Index", "Home", null)">View all alerts</a>
                    </div>
                </li>
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0 mr-lg-2">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out"></i>Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Navigation -->
    <div class="content-wrapper" style="background-image: url('@Url.Content("~/Content/Images/flight_bg.jpg")');background-repeat: no-repeat;
background-size: 100% 100%;">
        <div class="container-fluid">

            @RenderBody()
        </div>
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->

    <footer class="sticky-footer">
        <div class="container">
            <div class="text-center">
                <small>Copyright © UIA Flight Booking System 2017</small>
            </div>
        </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
    <!-- Logout Modal-->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    @Html.ActionLink("Logout", "Index", "Login", null, new { @class = "btn btn-primary" })
                </div>
            </div>
        </div>
    </div>

    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/jquery.easing.min.js"></script>
    <!-- Page level plugin JavaScript-->
    <script src="~/Scripts/Chart.min.js"></script>
    <script src="~/Scripts/jquery.dataTables.js"></script>
    <script src="~/Scripts/dataTables.bootstrap4.js"></script>

    <script src="~/Scripts/sb-admin.min.js" type="text/javascript"></script>
    <!-- Custom scripts for this page-->
    <script src="~/Scripts/sb-admin-datatables.min.js"></script>
    <script src="~/Scripts/sb-admin-charts.min.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>

DDACAssignment/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title | Ukraine International Airlines</title>

    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/sb-admin.css")
    @Styles.Render("~/Content/style.css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/dataTables.bootstrap4.css")
</head>

<body>
        <div class="container">

            @RenderBody()
        </div>


    <footer class="sticky-footer" style="width:100% !important">
        <div class="container">
            <div class="text-center">
                <small>Copyright © UIA Flight Booking System 2017</small>
            </div>
        </div>
    </footer>


    <script src="~/Scripts/jquery.min.js"></script>
    <script src="~/Scripts/popper.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Core plugin JavaScript-->
    <script src="~/Scripts/jquery.easing.min.js"></script>
    <script src="~/Scripts/sb-admin.min.js" type="text/javascript"></script>
</body>
</html>