DDACAssignment/Controllers/LoginController.cs
using DDACAssignment.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDACAssignment.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View("Login");
        }


        public ActionResult Login_User(string email, string password)
        {


            String connString = "Server=tcp:uiaflightddac.database.windows.net,1433;Initial Catalog=UIAFlight;Persist Security Info=False;User ID=web_user;Password=Abc123123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
            SqlConnection conn = new SqlConnection(connString);
            conn.Open();


            String query = "SELECT * FROM Person WHERE email = '" + email + "' AND password = '" + password + "'";


            SqlCommand cmd = new SqlCommand(query);
            cmd.CommandType = System.Data.CommandType.Text;
            cmd.Connection = conn;

            SqlDataReader reader = cmd.ExecuteReader();

            string temp = "";

            while (reader.Read())
            {

                Person.p.pid = (int)reader["id"];
                Person.p.fname = reader["fname"].ToString();
                Person.p.lname = reader["lname"].ToString();
                Person.p.contactNum = reader["contactNum"].ToString();
                Person.p.email = reader["email"].ToString();
                Person.p.password = reader["password"].ToString();

                
                conn.Close();
                return View("../Flight/Index");
            }

            conn.Close();



            TempData["loginFailed"] = "<script>alert('Login failed, please try again...');</script>";

            return View("Login");


        }
    }
}

DDACAssignment/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DDACAssignment.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        public ActionResult Index()
        {
            return View("../Login/Register");
        }
        public ActionResult Register_User(string fname, string lname, string contactNum, string email, string password)
        {

            //DONE Register

            String connString = "Server=tcp:uiaflightddac.database.windows.net,1433;Initial Catalog=UIAFlight;Persist Security Info=False;User ID=web_user;Password=Abc123123;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;";
            SqlConnection conn = new SqlConnection(connString);

            conn.Open();


            String query = "INSERT INTO [dbo].[Person] ([fname], [lname], [contactNum], [email], [password]) VALUES ('"+ fname +"', '"+ lname +"', '"+ contactNum+"', '"+ email +"', '" + password +"')";
            SqlCommand cmd = new SqlCommand(query);
            cmd.CommandType = System.Data.CommandType.Text;
            cmd.Connection = conn;
            cmd.ExecuteNonQuery();

            conn.Close();

            TempData["regisSuccess"] = "<script>alert('Account registered succesfully!!!');</script>";

            return View("../Flight/Index");
        }
    }
}

DDACAssignment/Views/Login/Login.cshtml
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
    ViewBag.Title = "Login";
}


<div class="card card-login mx-auto mt-5">
    <div class="card-header">Login</div>
    <div class="card-body">
@using (Html.BeginForm("Login_User", "Login"))
{
            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                @Html.TextBox("email", null, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                @Html.TextBox("password", null, new { @type="password", @class = "form-control" })
            </div>
            <div class="form-group">
                <div class="form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox"> Remember Password
                    </label>
                </div>
            </div>

            <input type="submit" class="btn btn-success btn-block" value="Login">
}
        <div class="text-center">
            <a class="d-block small mt-3" href="@Url.Action("Index", "Register", null)">Register an Account</a>
        </div>
    </div>
</div>

@Html.Raw(TempData["loginFailed"])

DDACAssignment/Views/Login/Register.cshtml
@{

    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
    ViewBag.Title = "Register";
}

<div class="card card-register mx-auto mt-5">
    <div class="card-header">Register an Account</div>
    <div class="card-body">
        @using (Html.BeginForm("Register_User", "Register")) {
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <label for="exampleInputName">First name: </label>

                        @Html.TextBox("fname", null, new { @class = "form-control" })
                    </div>
                    <div class="col-md-6">
                        <label for="exampleInputLastName">Last name: </label>
                        @Html.TextBox("lname", null, new { @class = "form-control" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="exampleInputContactNum1">Contact: </label>
                @Html.TextBox("contactNum", null, new { @class = "form-control" })
            </div>

            <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                @Html.TextBox("email", null, new { @class = "form-control" })
            </div>
            <div class="form-group">
                <div class="form-row">
                    <div class="col-md-6">
                        <label for="exampleInputPassword1">Password</label>
                        @Html.TextBox("password", null, new { @class = "form-control" , @type = "password" })
                    </div>
                    <div class="col-md-6">
                        <label for="exampleConfirmPassword">Confirm password</label>
                        @Html.TextBox("password2", null, new { @class = "form-control", @type = "password" })
                    </div>
                </div>
            </div>
            <input type="submit" class="btn btn-primary btn-block" value="Register">
        }
        <div class="text-center">
            <a class="d-block small mt-3" href="@Url.Action("Index", "Login", null)">Login Page</a>
        </div>
    </div>
</div>

@Html.Raw(TempData["regisSuccess"])